name: Python Hata Kontrolü

on: [push]

jobs:
  kod_kontrol:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Adım: GitHub'ın sanal makinesi senin kodlarını kendi içine çeker.
    - name: Kodu Çek
      uses: actions/checkout@v3

    # 2. Adım: Sanal makineye Python kurulur.
    - name: Python Ortamını Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Adım: Kodunda kritik bir yazım/mantık hatası var mı diye Flake8 aracı çalıştırılır.
    - name: Hata Tarayıcıyı (Flake8) Çalıştır
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
